--- #YAML:1.0
name:                Eidolon-Driver-Template-HTML
version:             0.01
abstract:            Eidolon HTML::Template driver.
license:             ~
author:              
    - Anton Belousov <abel@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Eidolon:                       0.02
    HTML::Template:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
